### ISSUE TITLE
Witness Node Problem

### ISSUE THREAD

**Issue by bangzi1001** [scorum/scorum#185]
My witness node encounter errors below and unable to produce blocks, thus I switch to backup server. I don't think is latency problem because I am running the witness node for BTS testnet server and it is doing well during witness node encounter problem.

    {"new_block":{"previous":"0018da4e903c3736e61a325249ac09fc2f9544d6","timestamp":"2018-05-19T12:44:12","witness":"xpss","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"1f253eea2a2761bd449690a2a0c968572181fae18d2c750cf3a251981707c205504a96c120a3d2d17a361e788da77730af0621c8b191ef3a2f75010426a0b85059","transactions":[]}}
    th_a  database.cpp:473 operator()
2658736ms th_a       application.cpp:608           handle_block         ] Error when pushing block:
4080000 unlinkable_block_exception: unlinkable block
block does not link to known chain
    {}
    th_a  fork_database.cpp:66 _push_block

    {}
    th_a  database.cpp:597 _push_block

    {"new_block":{"previous":"0018da4e903c3736e61a325249ac09fc2f9544d6","timestamp":"2018-05-19T12:44:12","witness":"xpss","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"1f253eea2a2761bd449690a2a0c968572181fae18d2c750cf3a251981707c205504a96c120a3d2d17a361e788da77730af0621c8b191ef3a2f75010426a0b85059","transactions":[]}}
    th_a  database.cpp:473 operator()
2658737ms th_a       fork_database.cpp:45          push_block           ] Pushing block to fork database that failed to link: 0018da50b4af2c0d4b6b35a3b503956605486a51, 1628752
2658737ms th_a       fork_database.cpp:45          push_block           ] Pushing block to fork database that failed to link: 0018da50b4af2c0d4b6b35a3b503956605486a51, 1628752
2658737ms th_a       fork_database.cpp:46          push_block           ] Head: 1628604, 0018d9bcaf33571463e21a73a799bc0da84d9689
2658737ms th_a       fork_database.cpp:46          push_block           ] Head: 1628604, 0018d9bcaf33571463e21a73a799bc0da84d9689
2658737ms th_a       application.cpp:608           handle_block         ] Error when pushing block:
4080000 unlinkable_block_exception: unlinkable block
block does not link to known chain
    {}
    th_a  fork_database.cpp:66 _push_block

    {}
    th_a  database.cpp:597 _push_block

    {"new_block":{"previous":"0018da4fbe14e991d069f5516142c83a00bad887","timestamp":"2018-05-19T12:44:15","witness":"real","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"1f1de39bdb045c589f0751b970d0e69342a1dcd19c6c1410b9a0dcb9a24c854c824b85ebfde99987eb0ce2924a4c28b7ee383ed0885f31da3a57a81d88d6c11451","transactions":[]}}
    th_a  database.cpp:473 operator()
2658737ms th_a       application.cpp:608           handle_block         ] Error when pushing block:
4080000 unlinkable_block_exception: unlinkable block
block does not link to known chain
    {}
    th_a  fork_database.cpp:66 _push_block

    {}
    th_a  database.cpp:597 _push_block

    {"new_block":{"previous":"0018da4fbe14e991d069f5516142c83a00bad887","timestamp":"2018-05-19T12:44:15","witness":"real","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"1f1de39bdb045c589f0751b970d0e69342a1dcd19c6c1410b9a0dcb9a24c854c824b85ebfde99987eb0ce2924a4c28b7ee383ed0885f31da3a57a81d88d6c11451","transactions":[]}}
    th_a  database.cpp:473 operator()

**Comment by educatedwarrior** [comment]
Have you tried deleting the db and doing a resync?   Also check stale block production is diabled in your config file?

**Comment by bangzi1001** [comment]
Have you tried deleting the db and doing a resync? Yes. This fix the issue and hopefully it won't come again.

Also check stale block production is diabled in your config file? Yes. The default setting actually is disable stale block production.

**Comment by abolinbsu** [comment]
The issue was solved within 0.0.3 version.
